### ISSUE TITLE
Does not work.....

### ISSUE THREAD

**Issue by Dodgerules** [bartbutenaers/node-red-contrib-alexa-notifyme#1]
I have tried using this node but have no success.  I have simply but the notify node into a flow with a timestamp to trigger. entered a simple text and access number. but not notifications on my Alexa device. Please elaborate what I could be doing wrong.

**Comment by juggledad** [comment]
Try this, instead of sending a timestamp in the inject node - put in a string of words and then remove the data in the 'notification' field of the node. 

Currently there isn't a way to trigger using just the data that is in the 'notification' feild and I'm looking at it.

**Comment by Dodgerules** [comment]
Yes that works fine. Keep up the amazing work......

**Comment by juggledad** [comment]
BTY, I  fixed up the node and am waiting for Burt to apply the changes tomorrow. It will check if you have an Access Code entered, check the data type of msg.payload. Only use msg.payload if the notification field in the node is empty.
