### ISSUE TITLE
activation with non US account

### ISSUE THREAD

**Issue by ThomasPoett** [bartbutenaers/node-red-contrib-alexa-notifyme#7]
any how possible you release the skill in other geographical regions too?

**Comment by bartbutenaers** [comment]
Hi Thomas,
I'm afraid I won't be able to help you with this.  The skill has been written by [Thomptronics ](https://www.thomptronics.com/about).  If you can't get the skill working, you will have to contact Thomptronics to find a solution.

Feel free to re-open this issue, if you have afterwards any concerns directly related to this node!

Kind regards,
Bart
