### ISSUE TITLE
Can not obtain the skill with non-US Amazon account

### ISSUE THREAD

**Issue by xbln** [bartbutenaers/node-red-contrib-alexa-notifyme#8]
The skill is only obtainable with US-Amazon Accounts. Please make it obtainable also for non-US accounts.

**Comment by bartbutenaers** [comment]
Hi,

This is a duplicate of another [issue](https://github.com/bartbutenaers/node-red-contrib-alexa-notifyme/issues/7).  Since I cannot solve it, I will close this also.

Bart
